spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://demologin2.c8a58wttwocm.ap-northeast-2.rds.amazonaws.com:5432/jwtlogin
    username: benew
    password: ehdfyrkehofk
  redis:
    host: localhost
    port: 5432


  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M